### ISSUE TITLE
IndexOutOfRangeExceptions

### ISSUE THREAD

**Issue by tarunchopra** [OfficeDev/Office-Inspectors-for-Fiddler#15]
Hi, 

 NSPI requests are being decoded now. However I have seen several IndexOutOfRangeExceptions. Seems like Decompression function is failing. I have seen such issues before ( with emsmdb requests) but could not conclusively determine where was the issue. 

Please see trace and screenshot below.
https://www.dropbox.com/s/thxhsux7ksnet7b/session_2916.saz?dl=0
https://www.dropbox.com/s/tqkdncfezh7uh6p/Screenshot%202016-01-29%2022.17.18.png?dl=0

Thanks.

**Comment by tarunchopra** [comment]
Issue stands resolved and latest code is checked in.

**Comment by aongeek** [comment]
It works. Thanks for the fix.

**Comment by JinghuiZhang-MSFT** [comment]
The issue has been fixed and closing this issue.
