### ISSUE TITLE
InvalidCastException Errors

### ISSUE THREAD

**Issue by aongeek** [OfficeDev/Office-Inspectors-for-Fiddler#17]
Hi, 

I am seeing this issue quite often "System.InvalidCastException: Specified cast is not valid.". 

Here is the download link for captured session. 
https://www.dropbox.com/s/qcn95on79mj4my4/invalid_cast.saz?dl=0

Thanks

**Comment by tarunchopra** [comment]
Hello Aongeek

Thanks for reporting the issue.We are looking into it.

Regards

**Comment by tarunchopra** [comment]
Hello Aongeek

We have checked in the fix, can you please get latest code and verify?

^TC

**Comment by aongeek** [comment]
So far I haven't seen this exception. Looks like the issue has been resolved.

Thanks.
