### ISSUE TITLE
HexBox dependency

### ISSUE THREAD

**Issue by st-gwerner** [OfficeDev/Office-Inspectors-for-Fiddler#24]
We are trying to use the MAPI Inspector for Fiddler to debug some traffic and are encountering an exception.  To isolate the exception, we are attempting to build the MAPI inspector from the source code. 
 
However, there is a dependency that we don’t recognize: Be.Windows.Forms.HexBox.
 
Searching Nuget reveals a 1.6 and 1.6.1 version of that control, but there are significant syntactical differences between those versions and whatever version the MAPI Inspector is using.

Can you provide a link to this package or update the readme to point to where it can be found?

If you go the readme route, I’d also suggest telling people the updated location of the fiddler exe under %LOCALAPPDATA%\Programs\Fiddler.

**Comment by st-gwerner** [comment]
Discovered that the used Be.Windows.Forms.HexBox.dll is actually in the Fiddler directory and distributed by them.  So my only comment on this then would be to add a paragraph to the readme about how to build the projects and where to find the external references for new people to this project.

**Comment by tomjebo** [comment]
@st-gwerner I'm glad you found that. You'll notice that the Xceed compression library is also there. 
This is something that I ran into a year ago and talked to the folks who own this to get them to do just what you said but apparently it got dropped. Now that we have an issue open here as well we'll get it updated.
Thanks for bringing it to our attention (again).
