### ISSUE TITLE
Can't pars response from share point (ms-fsshttp)

### ISSUE THREAD

**Issue by abogatyrev** [OfficeDev/Office-Inspectors-for-Fiddler#35]
Hi, 
[here](https://github.com/OfficeDev/Office-Inspectors-for-Fiddler/files/2514831/sharepoint_test_docx_open.zip) you can find Fiddler dump with a trace of opening simple docx file from SharePoint 365.
FSSHTTPandWOPI plugin can't pars response for the first frame.
Exception is
`System.InvalidCastException: Unable to cast object of type 'System.String' to type 'FSSHTTPandWOPIInspector.Parsers.FsshttpbResponse'.
   at FSSHTTPandWOPIInspector.FSSHTTPandWOPIInspector.TryParseFSSHTTPBResponseMessage(Response[] Responses, Byte[] bytesFromHTTP)
   at FSSHTTPandWOPIInspector.FSSHTTPandWOPIInspector.ParseHTTPPayloadForFSSHTTP(HTTPHeaders responseHeaders, Byte[] bytesFromHTTP, TrafficDirection direction)
`

**Comment by tomjebo** [comment]
@abogatyrev The responses from O365 products may not be the same as those from Sharepoint on premise products (2013, 2016, etc...).  The Fiddler Inspectors in this repo are designed to parse [MS-FSSHTTP*] traffic between clients and the on premise versions of Sharepoint listed in the  5 Appendix A: Product Behavior section of those documents.

I've run into that same exception during testing and it's basically saying that things are out of expected sequence. That is what I would expect to see if parsing from O365 products as they are different than the on-prem products especially in FSSHTTP.

BTW, Andrey, I've submitted a PR that adds support for the binary item in the Leaf Node Data Object: Data Hash fields. You can take a look and use in your local inspector until it gets merged by the test team.

**Comment by abogatyrev** [comment]
Thanks Tom,
I will use that PR #36
