### ISSUE TITLE
"MagicNumber" still used in MAPI output for NspiGetProps

### ISSUE THREAD

**Issue by tomjebo** [OfficeDev/Office-Inspectors-for-Fiddler#40]
search on "MagicNumber" in the source and you'll see the label. 
[MS-OXCMAPIHTTP] 2.2.1.1 AddressBookPropertyValue Structure has been updated in the documentation and the field should be labelled: HasValue. 

HasValue (optional) (1 byte): An unsigned integer when the PropertyType ([MS-OXCDATA]
section 2.11.1) is known to be either PtypString, PtypString8, PtypBinary or PtypMultiple
([MS-OXCDATA] section 2.11.1). This field MUST contain either TRUE (0xFF) or FALSE (0x00). A

Please update the label in inspector output.

**Comment by XinwLi** [comment]
This is a document issue that is not fixed,in [MS-OXCDATA]. So pending fix this until the document issue be  fixed.

**Comment by tomjebo** [comment]
@XinwLi, has the TDI been resolved for [MS-OXCDATA] or are you expecting this to remain unresolved? If so, I will close this issue.

**Comment by XinwLi** [comment]
> @XinwLi, has the TDI been resolved for [MS-OXCDATA] or are you expecting this to remain unresolved? If so, I will close this issue.

hi Tom, I have checked the TDI state. But this TDI still not resolved.

**Comment by XinwLi** [comment]
fix this issue by pull request #55
