### ISSUE TITLE
Current FSSHTTPandWOPIFiddlerInspector.dll is not able to parse the upload traffic of any file to OneDrive

### ISSUE THREAD

**Issue by rreddy-ns** [OfficeDev/Office-Inspectors-for-Fiddler#59]
We have captured upload traffic of a xlsx file to OneDrive through excel app. Earlier we could see this traffic can be parsed by FSSHTTPandWOPIFiddlerInspector.dll, but its not able to parse the latest upload traffic. Can you please check the same.

**Comment by muhashaf** [comment]
Facing the same issue. Any help appreciated.

**Comment by ChangDu2021** [comment]
[ParserIssue.zip](https://github.com/OfficeDev/Office-Inspectors-for-Fiddler/files/8022420/ParserIssue.zip)
@rreddy-ns @muhashaf I am from Test Suite project team, and I am trying to repro this issue. Could you please help check if they are the issues that you have, please refer to screenshots and #16 #23 #49 #165 #198 #204 in attached traffic. You would be better if you could share your traffic with us. And we are working on it.

![image](https://user-images.githubusercontent.com/81283391/152958434-d56c6ccc-bfb2-48d3-8958-c8cce8320e48.png)
![image](https://user-images.githubusercontent.com/81283391/152958686-34e6dce1-db78-4529-a067-8c93c4ff0d3f.png)

**Comment by rreddy-ns** [comment]
> [ParserIssue.zip](https://github.com/OfficeDev/Office-Inspectors-for-Fiddler/files/8022420/ParserIssue.zip) @rreddy-ns @muhashaf I am from Test Suite project team, and I am trying to repro this issue. Could you please help check if they are the issues that you have, please refer to screenshots and #16 #23 #49 #165 #198 #204 in attached traffic. You would be better if you could share your traffic with us. And we are working on it.
> 
> ![image](https://user-images.githubusercontent.com/81283391/152958434-d56c6ccc-bfb2-48d3-8958-c8cce8320e48.png) ![image](https://user-images.githubusercontent.com/81283391/152958686-34e6dce1-db78-4529-a067-8c93c4ff0d3f.png)

@ChangDu2021 Thank you for reply.
Here I am attaching the traffic that was failed to be parsed by the inspector. The traffic is partially parsed by the inspector. Some of the metadata got parsed properly. But its failed to parse actual file data.
[excel.saz.zip](https://github.com/OfficeDev/Office-Inspectors-for-Fiddler/files/8023493/excel.saz.zip)

**Comment by rreddy-ns** [comment]
@ChangDu2021 Yes the traffic in red part is not parsed properly. We are not using any source code to upload a file to OneDrive. We are using excel app only to upload the files.

What I mean by 'It was working earlier' is, the fiddler inspector was able to parse the upload traffic to older versions of excel app. We do have the old har files that were collected earlier with older versions of excel app and those har files are parsed properly now also. We do not have the version info of older excel app.

I am attaching an old har file that is parsed properly.
[excelissue.saz.zip](https://github.com/OfficeDev/Office-Inspectors-for-Fiddler/files/8032670/excelissue.saz.zip)

**Comment by ChangDu2021** [comment]
@rreddy-ns The fix has been merged into master branch in below dev repository. Could you please check if it works at your side? If everything works, we will create a PR to product master branch.
https://github.com/xian-rong/Office-Inspectors-for-Fiddler/

**Comment by rreddy-ns** [comment]
@ChangDu2021 I have verified that the new code is able to parse the data as shown in below screenshot. The data element is extracted twice as shown below. You may proceed with your PR to master branch. Thank you for your support.

<img width="798" alt="image" src="https://user-images.githubusercontent.com/43805721/154263291-32e0ce2c-a927-4b40-a35c-ce9a92d71a41.png">

<img width="804" alt="image" src="https://user-images.githubusercontent.com/43805721/154267252-8a9fc5f5-7892-46dd-8c37-6a3031943bbf.png">

**Comment by ChangDu2021** [comment]
@rreddy-ns Could you please close this issue because this PR has been merged into master branch?

**Comment by rreddy-ns** [comment]
@ChangDu2021 Sure.
